In [2]:
import torch

In [3]:
x = torch.arange(4.0)
print(x)

tensor([0., 1., 2., 3.])


In [5]:
x.requires_grad_(True)
x.grad

In [7]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [8]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [11]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [14]:
x.grad.zero_()
y = x*x
y.backward(torch.ones_like(x)) #
x.grad

tensor([0., 2., 4., 6.])

In [15]:
x.grad.zero_()

y = x * x

u = y.detach().clone()

# 将u 作为常数进行处理
z = u*x

z.sum().backward()
x.grad # x.grad == u


tensor([0., 1., 4., 9.])

In [17]:
x.grad.zero_()
y.sum().backward()
x.grad # x.gram == 2 * x

tensor([0., 2., 4., 6.])

In [18]:
x.grad.zero_()
u = x*x*x

#
u.sum().backward()
x.grad # x.grad == 3 * x * x

tensor([ 0.,  3., 12., 27.])

In [19]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [22]:
d

tensor(1658.4838, grad_fn=<MulBackward0>)

In [23]:
a

tensor(0.2025, requires_grad=True)

In [26]:
a.grad

tensor(8192.)

In [ ]:
from torch import save
#matplotlib inline
import random
import torch

@save
def syn_data(w,b,num_examples):
    x  = torch.normal(0,1,(num_examples,w))
    y = torch.matmul(x,w) + b
    y += torch.normal(0,0.01,y.shape)
    return x,y.reshape((-1,1))

