池化层
- 降低卷积层对位置的敏感性
    - 模糊了特征的精确位置
- 降低对空间降采样表示的敏感性
    - 池化层赋予了模型一定的平移不变性

In [2]:
import torch
import torch.nn as nn

In [3]:
def pool2d(X,pool_size,mode='max'):
    """
    池化层
    :param X: 输入数据
    :param pool_size: 池化窗口大小
    :param mode: 池化方式，'max'或'avg'
    :return: 池化后的数据
    """
    p_h, p_w = pool_size

    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i + p_h, j:j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i + p_h, j:j + p_w].mean()
            else:
                raise ValueError("mode must be 'max' or 'avg'")
    return Y

In [4]:
X = torch.arange(16,dtype=torch.float32).reshape(1,1,4,4)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [5]:
pool  = nn.MaxPool2d(3)
pool(X)

tensor([[[[10.]]]])

In [7]:
pool = nn.MaxPool2d(3,padding=1,stride=2)
pool(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])